let shopItemsData = [
    {
      id: "jfhgbvnscs",
      name: "Casual Shirt",
      price: 45,
      desc: "Elevate your everyday style with our latest collection of casual shirts. Designed for comfort and versatility. Dress it up with chinos or keep it cool with jeans.",
      img: "images/img-1.jpg",
    },
    {
      id: "ioytrhndcv",
      name: "Office Shirt",
      price: 100,
      desc: "Upgrade your work wardrobe with shirts that make you feel as good as you look. Shop now and redefine office style.",
      img: "images/img-2.jpg",
    },
    {
      id: "wuefbncxbsn",
      name: "T Shirt",
      price: 25,
      desc: "Experience comfort like never before with our premium t-shirts. Soft, breathable, and made to last, these tees are perfect for everyday wear.",
      img: "images/img-3.jpg",
    },
    {
      id: "thyfhcbcv",
      name: "Mens Suit",
      price: 300,
      desc: "Whether you're dressing for a business meeting, a formal event, or a special occasion, our suits are designed to make a statement.",
      img: "images/img-4.jpg",
    },
    {
      id: "thiecbawdjksadjk",
      name: "Mens Tie",
      price: 25,
      desc: "Add the perfect finishing touch to your outfit. Shop our collection of men's ties and find the one that speaks to you.",
      img: "images/img-5.png",
    },
    {
      id: "iuertrywebncdjksadjk",
      name: "Casual shoes",
      price: 200,
      desc: "Choose from a variety of designs, colors, and materials to suit your taste. With cushioned insoles and durable construction, these shoes will keep you on your feet all day with ease.",
      img: "images/img-6.png",
    },
    {
      id: "thierytbvcbvzdhadjk",
      name: "black suit",
      price: 450,
      desc: "Elevate your wardrobe with the timeless elegance of our black suits. Perfect for business meetings, formal events, or special occasions, this suit offers a sleek and sophisticated look that never goes out of style.",
      img: "images/img-7.png",
    },
    {
      id: "trfoiwfcnbcawdjksadjk",
      name: "polo shirt",
      price: 45,
      desc: "The tailored fit and signature collar detail make it easy to dress up or down, depending on your mood.",
      img: "images/img-8.png",
    },
    {
      id: "cbvxbcvsceldk",
      name: "denim shirt",
      price: 85,
      desc: "Rediscover casual cool with our versatile denim shirts. Whether you're dressing up or keeping it laid-back, our denim shirts are designed to fit your style.",
      img: "images/img-9.png",
    },
    {
      id: "oiopijmjkhuihb",
      name: "denim pants",
      price: 120,
      desc: "Whether you're dressing up for a night out or keeping it casual for the weekend, our denim pants are the perfect fit.",
      img: "images/img-10.png",
    },
    {
      id: "oiopijewyiohbjhib",
      name: "basic cap",
      price: 35,
      desc: "Elevate your casual wardrobe with a cap that combines function and fashion. Get yours today and take on the day in style.",
      img: "images/img-11.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "leather boots",
      price: 350,
      desc: "The robust construction and sturdy soles ensure long-lasting wear, while the classic design makes them a timeless addition to your wardrobe.",
      img: "images/img-12.png",
    },
  ];
  
